#version: 0.2

#phases:
 # pre_build:
  #  commands:
   #   - echo Logging in to Amazon ECR...
    #  - aws --version
     # - REPO_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/go-ecs-demo"
     # - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI

 # build:
  #  commands:
   #   - echo Build started on `date`
    #  - docker build -t go-ecs-demo .
     # - docker tag go-ecs-demo:latest $REPO_URI:latest

 # post_build:
  #  commands:
   #   - echo Build completed on `date`
    #  - docker push $REPO_URI:latest
    #  - printf '[{"name":"go-ecs-demo","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json

#artifacts:
 # files:
  #  - imagedefinitions.json

version: 0.2

phases:
  pre_build:
    commands:
     - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 481071950406.dkr.ecr.ap-south-2.amazonaws.com


  build:
    commands:
      - docker build -t go-cicd-demo .
      - docker tag go-cicd-demo:latest 481071950406.dkr.ecr.ap-south-2.amazonaws.com/go-cicd-demo:latest
      - docker push 481071950406.dkr.ecr.ap-south-2.amazonaws.com/go-cicd-demo:latest

  post_build:
    commands:
      - echo "=== AWS identity ==="
      - aws sts get-caller-identity

      - echo "=== Configuring kubectl for EKS ==="
      - aws eks update-kubeconfig --region ap-south-2 --name go-cidd-eks
     
      - echo "=== kubectl context ==="
      - kubectl config current-context
      - kubectl get nodes
      
      - echo "Applying Kubernetes manifests"
      - kubectl apply -f k8s/namespace.yml
      - kubectl apply -f k8s/

